# a set of partially bound statements (ie, some terms in the statement(s) are
# variables, starting with a '?')
string[] patterns

# if true, the event is automatically removed after it is triggered once
bool one_shot

string[] models

---
# Result:

# the event id.
string id

# topic to subscribe to to be notified 
# every time the event is triggered.
string topic

