# a set of partially bound statements (ie, some terms in the statement(s) are
# variables, starting with a '?')
string[] patterns

# the variables you want to be returned. If empty, all variables found in the
# patterns are returned
string[] vars

string[] models

---
# Result:
bool success

# a JSON-encoded list of dictionaries, representing the result of the FIND
# method. Each key in the dictionaries correspond to one variable.
string json

# if success = False, error_msg might contain additional information about the
# failure.
string error_msg


