string[] patterns
string[] vars # the variables you want to be returned. If empty, all variables found in the patterns are returned
string[] models
---
# result
string json # a JSON-encoded list of dictionaries, representing the result of the FIND method. Each key in the dictionaries correspond to one varaible.

