string ADD=add
string UPDATE=update
string RETRACT=retract
# alias for RETRACT
string REMOVE=retract
# alias for RETRACT
string DELETE=retract

# goal
string method
string[] statements
string[] models
duration lifespan # only relevant for ADD and UPDATE. Lifespan of 0 (default) means no expiration.
---
bool success # true if the triples were successfull added/deleted/updated

