##
## Modify the knowledge base (add,retract,update statements)
##

string ADD=add
string UPDATE=update
string RETRACT=retract
# alias for RETRACT
string REMOVE=retract
# alias for RETRACT
string DELETE=retract

string method
string[] statements
string[] models

# only relevant for ADD and UPDATE. Lifespan of 0 (default) means no expiration.
duration lifespan
---
# Result:

# true if the action was successfully performed
bool success

# if success = False, error_msg might contain additional information about the
# failure.
string error_msg

